import type { ApiProfile } from '@/profile-context'

export const PROFILE_GLYPHS = [
  { value: '◇', label: 'Diamond' },
  { value: '○', label: 'Circle' },
  { value: '□', label: 'Square' },
  { value: '△', label: 'Triangle' },
  { value: '☆', label: 'Star' },
  { value: '♡', label: 'Heart' },
  { value: '♧', label: 'Clover' },
  { value: '☾', label: 'Moon' },
  { value: '⌘', label: 'Command' },
  { value: '∞', label: 'Infinity' },
  { value: '◉', label: 'Target circle' },
  { value: '✦', label: 'Spark' },
  { value: '✧', label: 'Shine' },
  { value: '⚡', label: 'Lightning' },
  { value: '🔥', label: 'Fire' },
  { value: '🚀', label: 'Rocket' },
  { value: '💻', label: 'Computer' },
  { value: '🧠', label: 'Brain' },
  { value: '🤖', label: 'Robot' },
  { value: '✨', label: 'Sparkles' },
  { value: '🎯', label: 'Bullseye' },
  { value: '🛠️', label: 'Tools' },
  { value: '📚', label: 'Books' },
  { value: '📝', label: 'Notes' },
  { value: '📊', label: 'Chart' },
  { value: '🔬', label: 'Microscope' },
  { value: '🧪', label: 'Lab' },
  { value: '🔧', label: 'Wrench' },
  { value: '🧰', label: 'Toolbox' },
  { value: '🌐', label: 'Web' },
  { value: '☁️', label: 'Cloud' },
  { value: '🌙', label: 'Crescent moon' },
  { value: '☀️', label: 'Sun' },
  { value: '⭐', label: 'Gold star' },
  { value: '🌟', label: 'Glowing star' },
  { value: '💡', label: 'Idea' },
  { value: '🔍', label: 'Search' },
  { value: '🎨', label: 'Art' },
  { value: '🎵', label: 'Music' },
  { value: '🎙️', label: 'Microphone' },
  { value: '🎧', label: 'Headphones' },
  { value: '📷', label: 'Camera' },
  { value: '🎬', label: 'Film' },
  { value: '🖼️', label: 'Picture' },
  { value: '🎮', label: 'Game' },
  { value: '♟️', label: 'Chess' },
  { value: '🧩', label: 'Puzzle' },
  { value: '🛡️', label: 'Shield' },
  { value: '🔒', label: 'Lock' },
  { value: '🔑', label: 'Key' },
  { value: '🏠', label: 'Home' },
  { value: '🏢', label: 'Office' },
  { value: '🏗️', label: 'Construction' },
  { value: '🌱', label: 'Seedling' },
  { value: '🌿', label: 'Herb' },
  { value: '🍀', label: 'Lucky clover' },
  { value: '🌊', label: 'Wave' },
  { value: '🏔️', label: 'Mountain' },
  { value: '🌈', label: 'Rainbow' },
  { value: '🍎', label: 'Apple' },
  { value: '🍋', label: 'Lemon' },
  { value: '☕', label: 'Coffee' },
  { value: '🍕', label: 'Pizza' },
  { value: '🐧', label: 'Penguin' },
  { value: '🦊', label: 'Fox' },
  { value: '🐼', label: 'Panda' },
  { value: '🦉', label: 'Owl' },
  { value: '🐝', label: 'Bee' },
  { value: '🐙', label: 'Octopus' },
  { value: '🦄', label: 'Unicorn' },
  { value: '🐉', label: 'Dragon' },
  { value: '👾', label: 'Alien' },
  { value: '👻', label: 'Ghost' },
  { value: '💎', label: 'Gem' },
  { value: '🏆', label: 'Trophy' },
  { value: '🎁', label: 'Gift' },
  { value: '❤️', label: 'Red heart' },
  { value: '💜', label: 'Purple heart' },
  { value: '💙', label: 'Blue heart' },
  { value: '✅', label: 'Check' },
  { value: '❌', label: 'Cross' },
  { value: '⚙️', label: 'Gear' },
  { value: '📦', label: 'Package' },
  { value: '🗂️', label: 'Files' },
  { value: '🧭', label: 'Compass' },
] as const

const glyphs = new Set<string>(PROFILE_GLYPHS.map(option => option.value))

export function profileGlyph(profile: Pick<ApiProfile, 'type' | 'emoji'>) {
  if (profile.type === 'default') return '◎'
  return glyphs.has(profile.emoji) ? profile.emoji : PROFILE_GLYPHS[0].value
}
