FROM ghcr.io/tashfeenahmed/freellmapi:latest

ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=3001
ENV FREEAPI_BLOCK_PRIVATE_PROVIDER_URLS=true
ENV REQUEST_ANALYTICS_RETENTION_DAYS=90
ENV REQUEST_ANALYTICS_MAX_ROWS=100000

EXPOSE 3001